repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        # Format only the files that have been modified. If we format would every file in the repo, it would be to slow.
        # --diff-filter=ACMRTUXB filters out the files that have been deleted
        # sed -e "s/^server\///" removes the server/ prefix from the file name. Gofmt cannot find files for example /server/main.go
        entry: bash -c 'gofmt -l -w $(git diff --diff-filter=ACMRTUXB --name-only --cached | grep .go | sed -e "s/^server\///") ; git add -u' --
        # Format all files in the repo. It is slow, so we prefer to format only the files that have been modified.
        # entry: bash -c 'gofmt -l -w $(ls -d -- */ | grep -v vendor/ ; ls | grep *.go) ; git add -u' --
        language: golang
        files: \.go$
    # TODO add hook for go unit tests.
    # We should create a test suite that contains only unit tests that can be run without database connection etc
