# WasmPath = ""
enable_tailwind = true
http = "8080"
root = "."
tailwind_exec = "./tailwindcss"
tmp_dir = "tmp"
use_air = true
wasm_file = "main.wasm"

[build]
  args_bin = []
  bin = "new_wasm run"
  cmd = "new_wasm build"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  full_bin = "new_wasm run"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "css"]
  kill_delay = "400ns"
  log = "air.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
